// Parity test: asserts the TS engine (engine.ts) reproduces the Python
// engine's outputs exactly (within 1e-6) over the shared fixtures.
//
// expected.json is generated by running the REAL Python engine
// ("C:\Users\micha\MDD\schedule builder\engine") over the same fixtures via
// a generator script (see parity/expected.json header comment in the repo
// task notes). Run with: npm run test:engine

import { generate, scheduleScore, rankSchedules } from "./engine";
import { DEMO_DATA } from "./fixtures";
import type { Prefs } from "./types";
import expectedJson from "./parity/expected.json";

const EPS = 1e-6;

interface ExpectedSectionScore {
  crn: string;
  total: number;
  components: { prof_rating: number | null; gpa: number | null; time_fit: number };
}

interface ExpectedSchedule {
  crns: string[];
  total: number;
  total_6dp: string;
  section_scores: ExpectedSectionScore[];
  schedule_factors: Record<string, number>;
}

interface ExpectedCase {
  name: string;
  prefs: Prefs;
  generated: ExpectedSchedule[];
  ranked: Array<{ crns: string[]; total: number }>;
}

const expected = expectedJson as unknown as { cases: ExpectedCase[] };

let failures = 0;
let checks = 0;

function fail(msg: string): void {
  failures += 1;
  console.error(`  FAIL: ${msg}`);
}

function checkClose(actual: number, exp: number, label: string): void {
  checks += 1;
  if (!(Math.abs(actual - exp) <= EPS)) {
    fail(`${label}: expected ${exp}, got ${actual} (diff ${Math.abs(actual - exp)})`);
  }
}

function checkEqual(actual: unknown, exp: unknown, label: string): void {
  checks += 1;
  if (actual !== exp) {
    fail(`${label}: expected ${JSON.stringify(exp)}, got ${JSON.stringify(actual)}`);
  }
}

function checkComponent(
  actual: number | null,
  exp: number | null,
  label: string,
): void {
  if (exp === null || actual === null) {
    checkEqual(actual, exp, label);
  } else {
    checkClose(actual, exp, label);
  }
}

for (const testCase of expected.cases) {
  console.log(`case: ${testCase.name}`);
  const prefs = testCase.prefs;

  // 1. generate() must produce the same combinations in the same order.
  const combos = generate(DEMO_DATA.sectionsByCourse);
  checkEqual(combos.length, testCase.generated.length, `${testCase.name}: combo count`);

  const n = Math.min(combos.length, testCase.generated.length);
  for (let i = 0; i < n; i++) {
    const exp = testCase.generated[i];
    const sections = combos[i];
    checkEqual(
      sections.map((s) => s.crn).join(","),
      exp.crns.join(","),
      `${testCase.name}: combo[${i}] CRNs`,
    );

    // 2. scheduleScore() totals, per-section scores, and factors.
    const result = scheduleScore(sections, DEMO_DATA.rmp, DEMO_DATA.grades, prefs);
    checkClose(result.total, exp.total, `${testCase.name}: combo[${i}] total`);
    checkEqual(
      result.total.toFixed(6),
      exp.total_6dp,
      `${testCase.name}: combo[${i}] total to 6dp`,
    );

    checkEqual(
      result.sectionScores.length,
      exp.section_scores.length,
      `${testCase.name}: combo[${i}] section count`,
    );
    for (let j = 0; j < exp.section_scores.length; j++) {
      const expSec = exp.section_scores[j];
      const actSec = result.sectionScores[j];
      const label = `${testCase.name}: combo[${i}] section[${j}] (crn ${expSec.crn})`;
      checkEqual(result.sections[j].crn, expSec.crn, `${label} crn`);
      checkClose(actSec.total, expSec.total, `${label} total`);
      checkComponent(actSec.components.prof_rating, expSec.components.prof_rating, `${label} prof_rating`);
      checkComponent(actSec.components.gpa, expSec.components.gpa, `${label} gpa`);
      checkClose(actSec.components.time_fit, expSec.components.time_fit, `${label} time_fit`);
    }

    for (const [key, expVal] of Object.entries(exp.schedule_factors)) {
      const actVal = result.schedule_factors[key];
      checks += 1;
      if (actVal === undefined) {
        fail(`${testCase.name}: combo[${i}] missing schedule_factors.${key}`);
      } else {
        checkClose(actVal, expVal, `${testCase.name}: combo[${i}] schedule_factors.${key}`);
      }
    }
  }

  // 3. rankSchedules() must reproduce the Python ranking order exactly.
  const ranked = rankSchedules(DEMO_DATA, prefs);
  checkEqual(ranked.length, testCase.ranked.length, `${testCase.name}: ranked count`);
  const m = Math.min(ranked.length, testCase.ranked.length);
  for (let i = 0; i < m; i++) {
    checkEqual(
      ranked[i].sections.map((s) => s.crn).join(","),
      testCase.ranked[i].crns.join(","),
      `${testCase.name}: ranked[${i}] CRNs`,
    );
    checkClose(ranked[i].total, testCase.ranked[i].total, `${testCase.name}: ranked[${i}] total`);
  }
}

if (failures > 0) {
  console.error(`\nparity FAILED: ${failures} of ${checks} checks failed`);
  process.exit(1);
}
console.log(
  `\nparity OK: ${checks} checks passed across ${expected.cases.length} prefs cases (TS engine matches Python within 1e-6)`,
);
